const bcrypt = require('bcryptjs');

const data = {
    users: [
        {
            name: 'Arham',
            email: 'admin@example.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: true,
            isSeller: true,
            seller: {
                name: 'Puma',
                logo: '/images/logo1.png',
                description: 'best seller',
                rating: 4.5,
                numReviews: 120,
            },
        },
        {
            name: 'John',
            email: 'user@example.com',
            password: bcrypt.hashSync('56871243', 8),
            isAdmin: false,
        },
    ],
    products: [
        {
            // _id: '1',
            name: 'Nike Sneakers',
            // slug: "nike-sneaker",
            category: 'Shoes',
            image: '/images/product-1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description:
                "There's no need for frills when you're classic.The Nike Retro GTS is just that—a classically simple, always stylish canvas shoe.Nodding to the '96 original that gave a generation of skaters their don't-care attitude, the new design gets updated with a comfort insole, embroidered logos and metal eyelets.Featuring a canvas upper and tough rubber sole with heritage herringbone traction pattern, it lets you turn heads without trying.",
            countInStock: 5,
        },
        {
            // _id: `2`,
            name: 'Adidas Sneakers',
            // slug: "Adidas-sneaker",
            category: 'Shoes',
            image: '/images/product-1.jpg',
            price: 100,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'High quality product',
            countInStock: 3,
        },
        {
            // _id: `3`,
            name: 'Woodland Sneakers',
            // slug: "woodland-sneaker",
            category: 'Shoes',
            image: '/images/product-1.jpg',
            price: 100,
            brand: 'Woodland',
            rating: 3.7,
            numReviews: 10,
            description: 'High quality product',
            countInStock: 10,
        },
        {
            // _id: `4`,
            name: 'Puma Sneakers',
            // slug: "puma-sneaker",
            category: 'Shoes',
            image: '/images/product-1.jpg',
            price: 105,
            brand: 'Puma',
            rating: 4.0,
            numReviews: 10,
            description: 'High quality product',
            countInStock: 11,
        },
        {
            // _id: `5`,
            name: 'LV Sneakers',
            // slug: "LV-sneaker",
            category: 'Shoes',
            image: '/images/product-1.jpg',
            price: 103,
            brand: 'Nike',
            rating: 4.0,
            numReviews: 10,
            description: 'High quality product',
            countInStock: 1,
        },
        {
            // _id: `6`,
            name: 'Gucci Sneakers',
            // slug: "gucci-sneaker",
            category: 'Shoes',
            image: '/images/product-1.jpg',
            price: 125,
            brand: 'Gucci',
            rating: 5.0,
            numReviews: 10,
            description: 'High quality product',
            countInStock: 7,
        },
    ],
};

module.exports = data;
// export default data;
