const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Sneakers',
            category: 'Shoes',
            image: '/images/product-1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numberOfReviews: 10,
            description: 'High quality product',
            countInStock: 2,
        },
        {
            _id: `2`,
            name: 'Adidas Sneakers',
            category: 'Shoes',
            image: '/images/product-1.jpg',
            price: 100,
            brand: 'Adidas',
            rating: 4.0,
            numberOfReviews: 10,
            description: 'High quality product',
            countInStock: 7,
        },
        {
            _id: `3`,
            name: 'Woodland Sneakers',
            category: 'Shoes',
            image: '/images/product-1.jpg',
            price: 90,
            brand: 'Woodland',
            rating: 3.7,
            numberOfReviews: 10,
            description: 'High quality product',
            countInStock: 1,
        },
        {
            _id: `4`,
            name: 'Puma Sneakers',
            category: 'Shoes',
            image: '/images/product-1.jpg',
            price: 110,
            brand: 'Puma',
            rating: 4.0,
            numberOfReviews: 10,
            description: 'High quality product',
            countInStock: 20,
        },
        {
            _id: `5`,
            name: 'Nike Sneakers',
            category: 'Shoes',
            image: '/images/product-1.jpg',
            price: 50,
            brand: 'Nike',
            rating: 4.0,
            numberOfReviews: 10,
            description: 'High quality product',
            countInStock: 1,
        },
        {
            _id: `6`,
            name: 'Gucci Sneakers',
            category: 'Shoes',
            image: '/images/product-1.jpg',
            price: 105,
            brand: 'Gucci',
            rating: 5.0,
            numberOfReviews: 10,
            description: 'High quality product',
            countInStock: 20,
        },
    ],
};

export default data;
